services:
  gobackup:
    image: huacnlee/gobackup:latest
    container_name: gobackup
    restart: always
    ports:
      - "2703:2703"
    extra_hosts:
      - "xx.xxx.com:10.10.104.34"
    volumes:
      - './config:/etc/gobackup'
      - './data:/data'
    networks:
      - custom


networks:
  custom:
    driver: bridge
    ipam:
      config:
        - subnet: 172.88.0.0/16
          gateway: 172.88.0.1
